TARGET_DISK="/dev/vda"
HOSTNAME="my-void-pc"
TIMEZONE="Europe/Berlin"
LOCALE="en_US.UTF-8"
KEYBOARD_LAYOUT="de-latin1-nodeadkeys"
USERNAME="noeltz"
LIBC="glibc"
ROOT_FS="ext4"
ENABLE_SERVICES="dhcpcd"
BOOTLOADER="grub"
AUTO_REBOOT="false"
